title: Matt Pewsey
author:
  name: Matt Pewsey
  # email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Technical Blog on Engineering and Programming

show_excerpts: true # set to true to show excerpts on the homepage
excerpt_separator: <!--excerpt-->
exclude: ['README.md', '*.py', '*.sha256', 'Pipfile', 'Pipfile.lock', 'requirements.txt']
permalink: /:year/:month/:day/:title.html

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d %b %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  mpewsey
    rss: rss
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

header_pages:
  - archive.md
  - tags.md
  - tools.md
  - search.md

paginate: 10

# disqus:
  # shortname: mpewsey

google_analytics: G-5HZ0H32D9D

# Build settings
# theme: minima
remote_theme: jekyll/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme
 - jekyll-sitemap
 - jekyll-paginate
